# Generated by Django 4.2.9 on 2024-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='topic_Img',
            field=models.ImageField(default=1, upload_to='topic_images/'),
            preserve_default=False,
        ),
    ]
